### ISSUE TITLE
Any introduction on how JPro works internally?

### ISSUE THREAD

**Issue by wlnirvana** [jpro-one/jpro-documentation#1]
This is really a cool project that brings modern Java GUI  technology to the browser. Thanks for the brilliant job.

Is there a introduction to JPro internals? For example does it transpile Java code to HTML/CSS/JavaScript? (That is sort of what Vaadin is doing. UI components implemented both in server and in browser with HTML stuff.) Or does it implement the JavaFX infrastructure (or even the JVM) in browser using JavaScript so that JavaFX code runs smoothly in browser? What is the architecture of JPro?

**Comment by hhsandbaek** [comment]
How it works, in short:

**Comment by hhsandbaek** [comment]
How it works, in short: The Java apps run in a set of jvms hosted in some server/cloud.  Each jvm (JPro Server) serves as a container for a number of concurrent application sessions. The server code maintains a Javafx-scenegraph, which is being mirrored to the browser.  The js-code running in the browser (a) cooperates with the JPro server to map js-events into Javafx-events and (b) renders the Javafx scenegraph in the browser.  And, there are JPro libraries available to bridge between js and java, which enable for use of app- and platform-specific js code running in the browser, interfacing and cooperating with the java app.  Hope this helped for giving a basic picture!
